script.version=201805280000
neoid.toast.auth.url=http://auth.toast.com/authorize
neoid.bridge.url=https://id.payco.com/oauth2.0/login.nhn?m=bridge&client_id=db79th455Ku7UMi5cRL9&serviceProviderCode=CLOUD&access_token={accessToken}&nextUrl={nextUrl}&userLocale={userLocale}
neoid.join.url=https://id.payco.com/join.nhn?response_type=code&client_id=db79th455Ku7UMi5cRL9&serviceProviderCode=CLOUD
neoid.join.toastcloud.url=https://id.payco.com/oauth2.0/terms.nhn?response_type=code&client_id=db79th455Ku7UMi5cRL9&serviceProviderCode=CLOUD&token=
neoid.login.url=https://id.payco.com/oauth2.0/authorize?response_type=code&client_id=db79th455Ku7UMi5cRL9&serviceProviderCode=CLOUD
neoid.logout.url=https://auth.toast.com/logout
neoid.myinfo=https://id.payco.com/myinfo.nhn?serviceProviderCode=CLOUD&userLocale={userLocale}
neoid.withdraw=https://id.payco.com/withdraw.nhn?userLocale={userLocale}
neoid.personal.information.url=https://beta.toast.com/provision/privacy
neoid.autopayment.easyPayment=https://bill.payco.com/autoPayment/easyPayment
neoid.email.certificationUrl=https://id.payco.com/certificate/email/requestPreCertificate.nhn?id={id}&serviceProviderCode=CLOUD&authReason=EMAIL_CERTIFICATION&nextUrl=
neoid.toast.join.url=https://id.payco.com/serviceProvision.nhn?serviceProviderCode=CLOUD&nextUrl={nextUrl}
neoid.businessCertif=https://id.payco.com/businessCertif.nhn
user.locale.default=ko_KR
devcenter.url=https://beta.toast.com
cloud.url=http://beta-cloud.toast.com
console.url=https://beta-console.toast.com
member.url=https://beta-id.toast.com
iam.member.url=https://beta-iam.toast.com
iam.console.url=https://%s.beta-console.toast.com:
cs.url=//beta-cs.toast.com
inquiry.url=https://beta.toast.com/support/inquiry
docs.web.url=http://beta-docs.toast.com
infrastructure.computeNetwork.productId=KGDeiKUq
infrastructure.objectStorage.productId=Qy0caFux
product.inEnabled.list=appanalytics
kr1.server.ip.list=http://10.162.117.140:8080,http://10.162.117.141:8080
notice.serviceCode=2044054173
tc-role.appKey=dKQkCylbozg5aOmK
tc-role.secretKey=gxdZ86Oa
tc-role.domain=https://api-role.cloud.toast.com
meetup.web.url=http://beta-meetup.toast.com
meetup.web.posts=http://beta-meetup.toast.com/posts
cors.domains=*