script.version=201907100000
neoid.toast.auth.url=http://alpha-auth.toast.com/authorize
neoid.bridge.url=https://alpha-id.payco.com/oauth2.0/login.nhn?m=bridge&client_id=ALPEoUChg7HjPj4UF0C2&serviceProviderCode=CLOUD&access_token={accessToken}&nextUrl={nextUrl}&userLocale={userLocale}
neoid.join.url=https://alpha-id.payco.com/join.nhn?response_type=code&client_id=ALPEoUChg7HjPj4UF0C2&serviceProviderCode=CLOUD
neoid.join.toastcloud.url=https://alpha-id.payco.com/oauth2.0/terms.nhn?response_type=code&client_id=ALPEoUChg7HjPj4UF0C2&serviceProviderCode=CLOUD&token=
neoid.login.url=https://alpha-id.payco.com/oauth2.0/authorize?response_type=code&client_id=ALPEoUChg7HjPj4UF0C2&serviceProviderCode=CLOUD
neoid.logout.url=https://alpha-auth.toast.com/logout
neoid.myinfo=https://alpha-id.payco.com/myinfo.nhn?serviceProviderCode=CLOUD&userLocale={userLocale}
neoid.withdraw=https://alpha-id.payco.com/withdraw.nhn?userLocale={userLocale}
neoid.personal.information.url=https://alpha.toast.com/provision/privacy
neoid.autopayment.easyPayment=https://alpha-bill.payco.com/autoPayment/easyPayment
neoid.email.certificationUrl=https://alpha-id.payco.com/certificate/email/requestPreCertificate.nhn?id={id}&serviceProviderCode=CLOUD&authReason=EMAIL_CERTIFICATION&nextUrl=
neoid.toast.join.url=https://alpha-id.payco.com/serviceProvision.nhn?serviceProviderCode=CLOUD&nextUrl={nextUrl}
neoid.businessCertif=https://alpha-id.payco.com/businessCertif.nhn
user.locale.default=ko_KR
devcenter.url=https://alpha.toast.com
cloud.url=http://alpha-cloud.toast.com
console.url=http://dev-console.toast.com:8080
member.url=https://alpha-id.toast.com
iam.member.url=https://alpha-iam.toast.com
iam.console.url=http://%s.dev-console.toast.com:8080
cs.url=//alpha-cs.toast.com
inquiry.url=https://alpha.toast.com/support/inquiry
docs.web.url=http://alpha-docs.toast.com
infrastructure.computeNetwork.productId=KGDeiKUq
infrastructure.objectStorage.productId=Qy0caFux
product.inEnabled.list=appanalytics
server.ip.list=http://127.0.0.1:8080
notice.serviceCode=2044054173
tc-role.appKey=ACqqBWUY6eCl8jAI
tc-role.secretKey=yVusQekA
tc-role.domain=https://api-role.cloud.toast.com
meetup.web.url=http://alpha-meetup.toast.com
meetup.web.posts=http://alpha-meetup.toast.com/posts
cors.domains=*